name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 9.0.201

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Pack CSQLY
      run: dotnet pack CSQLY/CSQLY.csproj --no-build --configuration Release --output nuget-packages

    - name: Pack CSQLY.CLI
      run: dotnet pack CSQLY.CLI/CSQLY.CLI.csproj --no-build --configuration Release --output nuget-packages

    - name: Publish NuGet package
      run: |
        for f in ./nuget-packages/*.nupkg
        do
          dotnet nuget push "$f" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        done
